### ISSUE TITLE
turn:lanes on bidirectional way warning on junction=roundabout

### ISSUE THREAD

**Issue by danfos** [geofabrik/osmi_simple_views#12]
OSM inspector Highways view is showing warnings "turn:lanes on bidirectional way" for ways tagged as junction=roundabout but without "oneway=yes"

The wiki on [junction=roundabout](https://wiki.openstreetmap.org/wiki/Tag:junction%3Droundabout) indicates "Implies oneway=yes" so no warning should be given for this.

For an example see http://tools.geofabrik.de/osmi/?view=geometry&lon=4.50851&lat=51.87097&zoom=13:

![Screenshot_20191109_120603](https://user-images.githubusercontent.com/8472097/68527631-f6840b00-02e0-11ea-8aa7-408953fc5c83.png)

**Comment by Nakaner** [comment]
Thank you for the bug report. I agree that this is a bug (I totally forgot roundabouts and `turn:lanes=*` is unusual in roundabouts).

The correct link would have been this: http://tools.geofabrik.de/osmi/?view=highways&lon=4.52913&lat=51.89481&zoom=18
