### ISSUE TITLE
Open exact item in iD

### ISSUE THREAD

**Issue by thibaultmol** [geofabrik/osmi_simple_views#13]
Hi,

Right now if you click on a selection and want to open it in the iD editor, it just opens iD at that location. 
While iD does have a url scheme for opening the exact item you've clicked on. 
(if it's a way, example would be: https://www.openstreetmap.org/edit?way=497000210#map=19/51.04960/3.71237 Instead of just the gps coordinates link that currently shows up in osmi)

**Comment by Nakaner** [comment]
This repository is for the code of the backend code finding the data errors, not the web frontend (tools.geofabrik.de) which has no issue tracker.

If you select a feature and it appears "Selection" panel, the "edit with X" buttons there point to the specific object by its ID. However, the edit buttons at the top of the page do not point to the object by its ID.
