### ISSUE TITLE
Specify layers when requesting tiles

### ISSUE THREAD

**Issue by blackboxlogic** [geofabrik/osmi_simple_views#15]
I hope this is an appropriate place to ask this question.

I'm using geofabrik address validation tiles as the background in iD and I wish I could specify which layers were included in the tile.

Here is a tile with all layers: https://tools.geofabrik.de/osmi/tiles/addresses/19/159648/191294.png

I want only these layers:
- addrx_on_nonclosed_way
- no_addr_street
- misformatted_housenumber_lenient
- street_not_found
- place_not_found

But I'm not sure how to express this in the request. I've tried:
https://tools.geofabrik.de/osmi/tiles/addresses/19/159648/191294.png?LAYERS=addrx_on_nonclosed_way%2Cno_addr_street%2Cmisformatted_housenumber_lenient%2Cstreet_not_found%2Cplace_not_found

Which I composed by borrowing the syntax I see working on views here:
https://tools.geofabrik.de/osmi/views/addresses/wxs?LAYERS=addrx_on_nonclosed_way%2Cno_addr_street%2Cmisformatted_housenumber_lenient%2Cstreet_not_found%2Cplace_not_found&FORMAT=image%2Fpng%3B%20mode%3D24bit&PROJECTION=EPSG%3A900913&DISPLAYPROJECTION=EPSG%3A4326&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-7834717.709262,5415403.2571031,-7834122.3364714,5415601.5156451&WIDTH=997&HEIGHT=332

Is it possible to specify layers with a tile request?

**Comment by Nakaner** [comment]
Sorry, this is the repository for the backend code producing shape files or SQlite files of the errors in OSM. The WMS and tile service is not handled by any public repository. Please contact info@geofabrik.de for issues related to the services hosted at tools.geofabrik.de.

**Comment by blackboxlogic** [comment]
Thank you for your quick response and suggestion for where to look!
