### ISSUE TITLE
How often OSMI updates?

### ISSUE THREAD

**Issue by matkoniecz** [geofabrik/osmi_simple_views#16]
I looked at http://tools.geofabrik.de/osmi/?view=tagging&lon=-70.32779&lat=41.68389&zoom=11 and https://wiki.openstreetmap.org/wiki/OSM_Inspector - and failed to find info

**Comment by woodpeck** [comment]
Most views update once per day. The last update of the view you are looking at is listed below the map frame. Some views contain data from different sources, in these cases it is possible that the last update is given as a range.
