### ISSUE TITLE
piste:type=* not accepted as feature tag

### ISSUE THREAD

**Issue by johsin18** [geofabrik/osmi_simple_views#2]
Respective nodes are shown as no_feature_tag_nodes, while piste:type=* seems to be a valid feature tag, as per
https://wiki.openstreetmap.org/wiki/Key:piste:type
e.g. piste:type=sled

**Comment by Nakaner** [comment]
@woodpeck

**Comment by woodpeck** [comment]
Deployed, new data should be visible tomorrow.

**Comment by johsin18** [comment]
Thank you.
