### ISSUE TITLE
Duplicated issues

### ISSUE THREAD

**Issue by Dimitar5555** [geofabrik/osmi_simple_views#30]
If you go to [here](https://tools.geofabrik.de/osmi/?view=routing&lon=-80.13188&lat=25.91210&zoom=18&overlays=islands_car) and from the data dropdown choose "Car" you will see that the same issue is repeated three times for the same way. Over [here](https://tools.geofabrik.de/osmi/?view=routing&lon=-80.13241&lat=25.90688&zoom=18&overlays=islands_car) it is repeated 4 times for the same way. As far as I can see it looks like that the error is repeated for every connection with another way. Is this the intended behavior?

**Comment by Nakaner** [comment]
OSM ways are split by GraphHopper at every node which is shared with other routable ways. Therefore, one OSM way can result in multiple edges in the graph. These edges are the output shown in the OSMI web interface. If a way is an island and split into multiple edges, it will be shown multiple times.

That's not a bug.
