### ISSUE TITLE
highway lanes (error: forward+backward != both) most likely not an error if both_ways is used

### ISSUE THREAD

**Issue by sun-geo** [geofabrik/osmi_simple_views#31]
The error: *"forward+backward != both"* seems wrong for cases when key `both_ways` is used, e.g.:

https://www.openstreetmap.org/way/114254926/history
http://tools.geofabrik.de/osmi/?view=highways&lon=8.26605&lat=49.11674&zoom=18&overlays=lanes

Wiki's for `both_ways`: 
* https://wiki.openstreetmap.org/wiki/Proposed_features/Suffix_both_ways
* https://wiki.openstreetmap.org/wiki/Key:lanes:both_ways

**Comment by deep-blue** [comment]
The key `both_ways` is not used in the code at all. Does anyone know how to contribute to this project?

**Comment by Nakaner** [comment]
Issue #53 is about the same and was fixed today.
