### ISSUE TITLE
Is Wishlist on the wiki page is actually a good place to propose improvements?

### ISSUE THREAD

**Issue by matkoniecz** [geofabrik/osmi_simple_views#37]
See https://wiki.openstreetmap.org/wiki/OSM_Inspector#Wishlist

**Comment by Nakaner** [comment]
No, the list is not the right place. Most of the entries old, some even about 14 years now. In that time, OSMI backends have been rewritten one or two times. Feel free to delete that section of the wiki page and use GitHub issues or emails instead.

**Comment by matkoniecz** [comment]
Section removed, I suspected that it is some mistake or really old abandoned idea but wanted to check
