### ISSUE TITLE
Incorrect city location

### ISSUE THREAD

**Issue by hanidaza** [geofabrik/osmi_simple_views#41]
Hi everyone,
I have a problem with the location of the city of Benghazi in Libya it's pointed incorrectly in the data of OSM, can anyone help me to relocate it into the right position as follows:
32.1194° N, 20.0868° E

Thanks in advance

**Comment by woodpeck** [comment]
This issue has nothing to do with the OSM inspector. Also, the city is placed correctly in OSM: https://www.openstreetmap.org/node/5431132268#map=11/32.1288/20.0823
