### ISSUE TITLE
misformatted_housenumber_lenient displays completely wrong data for an area

### ISSUE THREAD

**Issue by emersonveenstra** [geofabrik/osmi_simple_views#45]
I think this might be related to #36, but if you go to https://tools.geofabrik.de/osmi/?view=addresses&lon=-85.71871&lat=42.93305&zoom=11&overlays=misformatted_housenumber_lenient, all of the errors shown are for nodes that are in different states or countries

**Comment by woodpeck** [comment]
This is an operational error stemming from a bug with the way in which different regions are updated sequentially and the results then merged. It has been difficult to debug because it shows up only intermittently. We're looking into it.

**Comment by Nakaner** [comment]
We launched the new frontend yesterday which includes minor changes to the backend as well. @emersonveenstra Did this solve the issue?

**Comment by emersonveenstra** [comment]
yep, fixed it, thanks!
