### ISSUE TITLE
Documentation with a list of all quality-checks?

### ISSUE THREAD

**Issue by ppKrauss** [geofabrik/osmi_simple_views#7]
Example `self_intersection_ways` is one of them: there are a list with all, with basic a description?

**Comment by Nakaner** [comment]
Please click on the blue (i) icon in the upper left corner to get to the wiki page documenting the view. See https://wiki.openstreetmap.org/wiki/OSM_Inspector/Views/Geometry for further information about the layer `self_intersection_ways`.
