### ISSUE TITLE
PostGIS translation of all quality-checks?

### ISSUE THREAD

**Issue by ppKrauss** [geofabrik/osmi_simple_views#8]
I am interested in to translate all quality-checks (`duplicate_segment`, `way_in_multiple_rings`, etc.) to SQL/PostGIS functions... There are a place to discuss this kind of issue?

**Comment by Nakaner** [comment]
I don't understand why you want to use such a slow solution like PostgreSQL for things that could be solved using Osmium (C++ or Python) faster. However, we don't plan to migrate our C++ code to PostgreSQL. The predecessor of the predecessor of this project was implemented in PostgreSQL.

If you want to discuss software developing of quality assurance in general, please use the [Dev mailing list](https://lists.openstreetmap.org/listinfo/dev).
